### ISSUE TITLE
Error: Cannot find module '../handlers/Hive'

### ISSUE THREAD

**Issue by alcastelo** [cesarferreira/drone#12]
Hi there.
Im using Ubuntu linux, and drone is getting me this error message:

drone
module.js:491
    throw err;
    ^

Error: Cannot find module '../handlers/Hive'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/drone/src/metadata/utils.js:8:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/drone/src/metadata/metadata.js:9:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/drone/src/handlers/hive.js:9:18)
    at Module._compile (module.js:573:30)

After a little look about it, there seems that in the file src/metadata/utils.js , the line 8 is having : 
const Hive = require('../handlers/Hive'); 
where it should be:
const Hive = require('../handlers/hive');
since the file name  "hive.js" is un lowercase
can you please take a look???
Thanks a Lot

**Comment by cesarferreira** [comment]
nice catch!
Just released a new version `1.0.1` with that fixed,

Thanks a lot!

> npm install -g drone
