### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dumazy** [cesarferreira/drone#16]
Unable to use drone on Windows in Git Bash

```
$ drone update
C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\utils.js:19
function findSync(...args) {
                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\git.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

```
$ drone new
C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\utils.js:19
function findSync(...args) {
                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\git.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

```
$ drone
C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\utils.js:19
function findSync(...args) {
                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\frede\AppData\Roaming\npm\node_modules\drone\src\utils\git.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by cesarferreira** [comment]
That's because you have an old version of `node`, when they didn't have support for "infinite" parameters.

show me the result of this command: `node -v`

This should be fixed if you update your node (`brew update node`)

**Comment by dumazy** [comment]
node version: v4.6.0

**Comment by cesarferreira** [comment]
```
❯ node -v    
v8.6.0
```

You're a few versions behind :)
