### ISSUE TITLE
Adding Room dependency by google spitting odd error.

### ISSUE THREAD

**Issue by BrianLusina** [cesarferreira/drone#18]
Whenever I try adding the Room dependency by Google. I get this error
```
drone add google/room app
TypeError: GradleUtils.findLineToInsertDependency(...).then is not a function
    at handle (/usr/lib/node_modules/drone/src/tasks/add.js:19:5)
    at handleRepositoryInjection (/usr/lib/node_modules/drone/src/tasks/add.js:35:3)
    at hive.getWithVersions.then.info (/usr/lib/node_modules/drone/src/tasks/add.js:80:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
A drone search of the dependency:

```
drone search google/room
==> Found it!
google/room: Room provides an abstraction layer over SQLite to allow fluent database access while harnessing the full power of SQLite.
```

But, I can't add the dependency to the app module. This is the only issue I have found, I can easily add other dependencies without any issue:

An example.

``` bash
drone add reactivex/rxkotlin app                                                                         
==> Inserted the following line
implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'
```
> Adding rxkotlin dependency

**Comment by cesarferreira** [comment]
nice catch mate, found the issue, will push the changes after lunch :)

**Comment by BrianLusina** [comment]
Alright! Thanks for the quick response :+1:
