### ISSUE TITLE
Cannot find module '../drone-hive/hive'

### ISSUE THREAD

**Issue by ispam** [cesarferreira/drone#19]
Hello,

I am using Windows 10 and using command **drone info dagger** got this error:

```
Error: Cannot find module 'C:\Users\diego/.drone/drone-hive/hive/C:\Users\diego\.drone\drone-hive\hive\dagger.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.getLibraryDescription (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:27:12)
    at Object.getSuggestion (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:13:30)
    at items.forEach.item (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:20:24)
    at Array.forEach (<anonymous>)
    at Object.getSuggestions (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:19:11)
    at Object.showSuggestionsIfPresent (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\quick_search.js:98:33)
    at QuickSearch.search.then.results (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\tasks\info.js:27:23)
    at <anonymous>
```

**Comment by cesarferreira** [comment]
Just released `1.7.2`, see if it fixed it for you

**Comment by ispam** [comment]
Hi,

Updated to 1.7.2 and using same command as before got this new message:
`Error: C:\Users\diego/.drone/drone-hive/hive/C:\Users\diego\.drone\drone-hive\hive\dagger.json: ENOENT: no such file or directory, open 'C:\Users\diego\.drone\drone-hive\hive\C:\Users\diego\.drone\drone-hive\hive\dagger.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.readFileSync (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\node_modules\jsonfile\index.js:61:22)
    at Object.getLibraryDescription (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:29:21)
    at Object.getSuggestion (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:14:30)
    at items.forEach.item (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:21:24)
    at Array.forEach (<anonymous>)
    at Object.getSuggestions (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\suggestions.js:20:11)
    at Object.showSuggestionsIfPresent (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\handlers\quick_search.js:98:33)
    at QuickSearch.search.then.results (C:\Users\diego\AppData\Roaming\npm\node_modules\drone\src\tasks\info.js:27:23)`

**Comment by cesarferreira** [comment]
can you `add` or `test` ? is it just the `info` that behaves like this?

**Comment by ispam** [comment]
Out of all the commands, **update, list, stats and hive** are working.

**open**
![open](https://user-images.githubusercontent.com/4166274/39089850-66a07564-4595-11e8-8001-c722c4c0e668.png)
**remove**
![remove](https://user-images.githubusercontent.com/4166274/39089851-66b891b2-4595-11e8-8014-69d9ef456bb2.png)
**search**
![search](https://user-images.githubusercontent.com/4166274/39089853-66ccc754-4595-11e8-841d-caf6f37d421d.png)
**test**
![test](https://user-images.githubusercontent.com/4166274/39089854-66e091a8-4595-11e8-8a33-cccf752e984c.png)
**add**
![add](https://user-images.githubusercontent.com/4166274/39089856-66f568c6-4595-11e8-992c-ba6dd0f1da4d.png)
**install**
![install](https://user-images.githubusercontent.com/4166274/39089857-67095214-4595-11e8-89bd-52013379a5ba.png)

**Comment by cesarferreira** [comment]
I didn't build this tool with `windows` in mind, i don't own any windows machine to find out what's wrong, if you know `nodejs` can you try to fix it an open a pull request?

**Comment by ispam** [comment]
I'll try
